### ISSUE TITLE
Cache fails with zstd error - zstd -d: Cannot exec: No such file or directory

### ISSUE THREAD

**Issue by sammcj** [actions/cache#811]
Despite zstd being installed, the cache action fails as it appears to be looking for zstd in the wrong location.

- Operation System: Amazon Linux 2
- Action version: v3
- Runner version: Latest stable

Job:

```yaml
- uses: actions/checkout@v3
- name: Cache Maven repository
  uses: actions/cache@v3
  with:
    path: ~/.m2/repository
    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    restore-keys: |
      ${{ runner.os }}-maven-
```

```
Run actions/cache@v3
Received 0 of 4[7](https://github.com/OrgName/repo-name/runs/6702665797?check_suite_focus=true#step:3:8)5287217 (0.0%), 0.0 MBs/sec
Received 0 of 475287217 (0.0%), 0.0 MBs/sec
Received 4194304 of 4752[8](https://github.com/OrgName/repo-name/runs/6702665797?check_suite_focus=true#step:3:9)7217 (0.[9](https://github.com/OrgName/repo-name/runs/6702665797?check_suite_focus=true#step:3:10)%), 1.3 MBs/sec
Received 46137344 of 475287217 (9.7%), 11.0 MBs/sec
Received 83886080 of 475287217 (17.6%), 16.0 MBs/sec
Received [10](https://github.com/OrgName/repo-name/runs/6702665797?check_suite_focus=true#step:3:11)4857600 of 475287217 (22.1%), 16.7 MBs/sec
Received [13](https://github.com/OrgName/repo-name/runs/6702665797?check_suite_focus=true#step:3:14)4217728 of 475287217 (28.2%), 18.3 MBs/sec
Received 167772160 of 475287217 (35.3%), 20.0 MBs/sec
Received 197132288 of 475287217 (41.5%), 20.9 MBs/sec
Received 234881024 of 475287217 (49.4%), 22.4 MBs/sec
Received 268435456 of 475287217 (56.5%), 23.3 MBs/sec
Received 297795584 of 475287217 (62.7%), 23.6 MBs/sec
Received 339738624 of 475287217 (71.5%), 24.9 MBs/sec
Received 369098752 of 475287217 (77.7%), 25.1 MBs/sec
Received 406847488 of 475287217 (85.6%), 25.8 MBs/sec
Received 4362076[16](https://github.com/OrgName/repo-name/runs/6702665797?check_suite_focus=true#step:3:17) of 4752872[17](https://github.com/OrgName/repo-name/runs/6702665797?check_suite_focus=true#step:3:18) (91.8%), 26.0 MBs/sec
Received 471092913 of 475287217 (99.1%), 26.4 MBs/sec
Received 475287217 of 475287217 (100.0%), 26.2 MBs/sec
Cache Size: ~453 MB (475287217 B)
/bin/tar --use-compress-program zstd -d -xf /home/ec2-user/actions-runner/_work/_temp/469[19](https://github.com/OrgName/repo-name/runs/6702665797?check_suite_focus=true#step:3:20)ba1-0057-4976-990d-1f9cd28b3900/cache.tzst -P -C /home/ec2-user/actions-runner/_work/repo-name/repo-name
tar (child): zstd -d: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
Warning: Tar failed with error: The process '/bin/tar' failed with exit code 2
```

**Comment by caseyagraff** [comment]
Experiencing what I believe is a related error with cache@v2.

`Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_87e210c3-fb31-497b-9ab0-da952e03417f/5c14691f-39b6-4ada-a092-3021917c4b2d.tar.gz. return code: 2.`

**Comment by kickthemooon** [comment]
me too
```
tar -xzf
```

**Comment by sevenseacat** [comment]
Seeing the same error as caseyagraff.

```
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_4192251e-0ae7-4f05-b113-e03bf86b3a83/a97fb7bf-5285-4c84-aa2a-021debd0fb44.tar.gz. return code: 2.
```

**Comment by emilaasa** [comment]
Same tar error here, with some context:

```
Current runner version: '2.291.1'
Operating System
  Ubuntu
  20.04.4
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20220515.1
  Included Software: https://***.com/actions/virtual-environments/blob/ubuntu20/20220515.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://***.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220515.1
Virtual Environment Provisioner
  1.0.0.0-main-20220516-1
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
Download action repository 'actions/setup-java@v1' (SHA:d202f5dbf7256730fb690ec59f6381650114feb2)
Download action repository 'webfactory/ssh-agent@v0.4.1' (SHA:ee29fafb6aa450493bac9136b346e51ea60a8b5e)
Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_600c9728-0e67-43f3-ac10-17af2f8ecba0/b49c9e6c-5cf2-458a-bf4b-9a1363839462.tar.gz. return code: 2.
```

**Comment by puneet-traceable** [comment]
I could get around this by installing zstd using apt/yum package manager.

**Comment by sevenseacat** [comment]
Seems to be fixed now :)

**Comment by Speissi** [comment]
I was running `actions/cache@v2` and got the `Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_<random id>.tar.gz. return code: 2.` error. I then updated all my workflows to use `actions/cache@v3` and it seems to have fixed the problem.

**Comment by Minipada** [comment]
> I was running `actions/cache@v2` and got the `Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_<random id>.tar.gz. return code: 2.` error. I then updated all my workflows to use `actions/cache@v3` and it seems to have fixed the problem.

It unfortunately didn't solve my issue

**Comment by harupy** [comment]
Switching to v3 from v2 worked for me.

**Comment by tiwarishub** [comment]
👋 , 👀

**Comment by tiwarishub** [comment]
Trying to reproduce. I tried couple of workflow with v2 and v3. https://github.com/tiwarishub/empty/actions/workflows/test.yml but doesnt seems to be happening

**Comment by tiwarishub** [comment]
> Switching to v3 from v2 worked for me.

For anyone it is not working ?

**Comment by Speissi** [comment]
> @tiwarishub bumping to v3 resolved the issue. I believe it only happens on github hosted runners

I was actually using self-hosted runners with actions runner controller.

**Comment by tguilpain** [comment]
I have the same issue with 
```
##[debug]Download 'https://api.github.com/repos/actions/cache/tarball/937d24475381cd9c75ae6db12cb4e79714b926ed' to '/home/runner/work/_actions/_temp_6f6b38df-acb3-4cbc-a688-c0e1adfcf6cb/1e3524d5-210a-4d29-803d-46eeb869[56](https://github.com/acquia-pso/veolia/runs/6704394552?check_suite_focus=true#step:1:60)27.tar.gz'
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_6f6b38df-acb3-4cbc-a688-c0e1adfcf6cb/1e3524d5-210a-4d29-803d-46eeb8695627.tar.gz. return code: 2.
##[debug]System.NotSupportedException: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_6f6b38df-acb3-4cbc-a688-c0e1adfcf6cb/1e3524d5-210a-4d29-803d-46eeb8695627.tar.gz. return code: 2.
```
Seems to be due to https://api.github.com/repos/actions/cache/tarball/937d24475381cd9c75ae6db12cb4e79714b926ed being zero bytes

**Comment by tomgrossman** [comment]
> @tiwarishub bumping to v3 resolved the issue. I believe it only happens on github hosted runners

yep, bumping fixed the issue for us as well

**Comment by billy1624** [comment]
Same here:
- https://github.com/SeaQL/sea-orm/pull/783

**Comment by tiwarishub** [comment]
Error in description is while downloading the cache but in subsequent comments it for downloading the  tar ball of actions/cache  (which is different and seems to be happening for most). We were seeing issues with codeload which seems to be fixed now. We will update here once get more details

**Comment by tiwarishub** [comment]
It should be fixed, we have removed cached codeload file.
> Seems to be due to https://api.github.com/repos/actions/cache/tarball/937d24475381cd9c75ae6db12cb4e79714b926ed being zero bytes
 
@tguilpain now it should result to 1.1Mb file. Can you please check and see if this is working fine now for you ?

**Comment by tguilpain** [comment]
The job on v2 is still trying to pull https://api.github.com/repos/actions/cache/tarball/937d24475381cd9c75ae6db12cb4e79714b926ed and it still results in a zero bytes archive for me

**Comment by bhushan991** [comment]
> It should be fixed, we have removed cached codeload file.
> 
> > Seems to be due to https://api.github.com/repos/actions/cache/tarball/937d24475381cd9c75ae6db12cb4e79714b926ed being zero bytes
> 
> @tguilpain now it should result to 1.1Mb file. Can you please check and see if this is working fine now for you ?

Still Getting:
```
Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_0465fe7c-7a64-4409-827a-a2dfce55d668/e800866b-99b7-4df9-bd5a-b8dfb911fd5d.tar.gz. return code: 2.
```

**Comment by piotrekkr** [comment]
Upgrade to v3 is still not doing much for me:
![image](https://user-images.githubusercontent.com/503782/171589511-f0589b46-4a0e-4578-b5bb-5311b532a0b9.png)

**Comment by jontze** [comment]
Restarting the failed jobs multiple times seems to resolve the issue for me sometimes. I'm still on v2.

**Comment by piotrekkr** [comment]
I was using v3 and it failed again. But after enabling debug and rerunning seems like it is now working (at least it does not fail in same place as before).

**Comment by tiwarishub** [comment]
please let me know, if anyone still seeing this issue

**Comment by tguilpain** [comment]
Must be cached somewhere, when I click on the v2 link, it downloads a zero bytes archive for me.
V3 link is fine with 1,2MB

**Comment by jpmenil** [comment]
```
curl -sIL https://api.github.com/repos/actions/cache/tarball/937d24475381cd9c75ae6db12cb4e79714b926ed | grep content-length
content-length: 0
```
```
curl -sIL https://api.github.com/repos/actions/cache/tarball/30f413bfed0a2bc738fdfd409e5a9e96b24545fd | grep content-length
content-length: 0

**Comment by rusrushal13** [comment]
cc @tiwarishub 
```
curl -sIL https://api.github.com/repos/actions/setup-python/tarball/7f80679172b057fc5e90d70d197929d454754a5a | grep content-length                                                             
content-length: 0
```
I am still getting the same error from other repos

**Comment by tiwarishub** [comment]
```
curl -sIL https://api.github.com/repos/actions/setup-python/tarball/7f80679172b057fc5e90d70d197929d454754a5a | grep content-length                                                             
content-length: 0
```
above content length is of  302 response 

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/64764738/171607569-4efd9363-7c3b-476d-972f-4994e3418525.png">

**Comment by jpmenil** [comment]
true, seem to be better now. thx !!

**Comment by tguilpain** [comment]
I confirm my jobs run fine now, still on v2

**Comment by jontze** [comment]
The issue is resolved for me as well :+1:

**Comment by vsvipul** [comment]
Closing as resolved. Thank you @tiwarishub  for taking this up. 
Summary-
> Summarizing the issue:
We had an issue with codeload, which serves these archives, which resulting to 0mb. After the issue was resolved, some of host end up having 0mb archive and we deleted those cached files from hosts. but looks like some process have still kept this file in open state. So we redeployed error causing host to make sure no host have 0mb archive.
So now we should not have 0mb archive from https://api.github.com/repos/actions/cache/tarball/937d24475381cd9c75ae6db12cb4e79714b926ed (v2)
https://api.github.com/repos/actions/cache/tarball/30f413bfed0a2bc738fdfd409e5a9e96b24545fd (v3)
Both of the above should result non zero mb archives.

**Comment by sammcj** [comment]
There looks to still be an issue with actions/cache@v3 on the cleanup stage @vsvipul :

```
Post job cleanup.
/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/ec[2](https://github.com/OrgName/repo-name/runs/6750348758?check_suite_focus=true#step:10:2)-user/actions-runner/_work/repo-name/repo-name --files-from manifest.txt
tar (child): zstd -T0: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
Warning: Tar failed with error: The process '/bin/tar' failed with exit code null
```

**Comment by vsvipul** [comment]
@tiwarishub Can you please look further into @sammcj 's comment?

**Comment by tiwarishub** [comment]
@sammcj  this is different issue from the one which was discussed and resolved(it was related to setup of actions/cache and not related to error after restore of cache). 
To debug the issue more, i will need debug logs to get more info for failure related to zstd. I will also recommend to create a separate issue and tag me there because we have lot of participants in this issue. 🙇

**Comment by tiwarishub** [comment]
Okay, i found we already have one open issue related to this https://github.com/actions/cache/issues/809. Closing this and follow up there

**Comment by sammcj** [comment]
This is occurring again on the creation of cache

![Screen Shot 2022-06-22 at 11 04 40 am](https://user-images.githubusercontent.com/862951/174921571-ba010519-9d5d-4d5f-aca9-ae530c545940.jpg)

**Comment by sammcj** [comment]
FYI - after fixing this our Java builds have gone from 20-25mins right down to 5-7mins! 🎉

**Comment by DrashtyDadhaniya** [comment]
> Switching to v3 from v2 worked for me.

I am already using v3 and getting the same error then what can be done?
